In [49]:
import pandas as pd

In [50]:
data = pd.read_csv('Raw_data.csv')

In [51]:
data

,client_id,gender,birth_date,create_date,nonresident_flag,businessman_flag,city,term,contract_sum,product_category_name,...,card_type_name,start_date,fact_close_date,purchase_sum,purchase_count,current_balance_avg_sum,current_balance_sum,current_debit_turn_sum,current_credit_turn_sum,card_type
0,fe60b594364f9f636266ed1ef4f89c32,Ж,1985,2020-01-29,R,0,Гусь-Хрустальный,NaN,0.0,Договор на текущий счет для дебетовой карты,...,Visa Platinum Rewards,2019.0,2021.0,16600.0,71,39700.0,25700.0,220600.0,201000.0,dc
1,3012cabca5885ed53d348d6e57dab5de,М,1951,2009-09-24,R,0,Ишимбай,NaN,0.0,Договор на текущий счет для дебетовой карты,...,VISA Classic,2019.0,NaN,0.0,0,1900.0,1000.0,6200.0,3000.0,dc
2,d871ef96820b6c7a1ada8e01a772724e,Ж,1982,2006-12-25,R,0,Юрга,NaN,0.0,Договор на текущий счет для дебетовой карты,...,NaN,NaN,NaN,0.0,0,0.0,0.0,0.0,0.0,dc
3,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,0,Томск,NaN,0.0,Договор на текущий счет для дебетовой карты,...,Visa Rewards,2021.0,NaN,24300.0,118,0.0,0.0,35400.0,35400.0,cc
4,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,0,Томск,NaN,0.0,Договор на текущий счет для дебетовой карты,...,Eurocard/MasterCard World,2018.0,2022.0,24300.0,118,0.0,0.0,35400.0,35400.0,cc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371578,d69d3201104ab393c0638839a7284ad7,М,1953,2018-08-08,R,0,Пятигорск,NaN,200000.0,Кредитная карта,...,NaN,NaN,NaN,0.0,0,0.0,300.0,9900.0,10100.0,dc
371579,a936fb30e2268d2874cdcaa221032915,М,1997,2022-05-12,R,0,Кемерово,NaN,15000.0,Кредитная карта,...,NaN,NaN,NaN,15000.0,33,0.0,0.0,15000.0,15000.0,dc
371580,a9cf0bb4f06fa321704ced777e993b33,М,1983,2021-10-15,R,0,Санкт-Петербург,NaN,15000.0,Кредитная карта,...,NaN,NaN,NaN,600.0,5,0.0,0.0,1100.0,1100.0,dc
371581,f69eb17242ca85eb21349dc08220afb8,Ж,1986,2022-02-12,R,0,Уфа,NaN,15000.0,Кредитная карта,...,NaN,NaN,NaN,0.0,0,0.0,0.0,1100.0,1100.0,dc
371582,93237191eddf8dec77cc947c3c086358,Ж,1959,2012-07-19,R,0,Москва,NaN,30000.0,Кредитная карта,...,NaN,NaN,NaN,9900.0,19,0.0,0.0,29900.0,29900.0,dc

In [52]:
data.shape

(371583, 21)

Подготовка базы данных

In [53]:
data = data.drop(['term','businessman_flag'], axis=1)

In [54]:
data = data.fillna({'start_date': -1, 'fact_close_date': -1})

In [55]:
data = data.astype({'start_date': int, 'fact_close_date': int , 'purchase_sum':int ,'purchase_sum':int ,'contract_sum':int , 'current_balance_avg_sum':int , 'current_balance_sum':int, 'current_debit_turn_sum':int, 'current_credit_turn_sum':int})

In [56]:
data.shape

(371583, 19)

In [57]:
a = data['card_id'].value_counts()

In [58]:
data

,client_id,gender,birth_date,create_date,nonresident_flag,city,contract_sum,product_category_name,card_id,card_type_name,start_date,fact_close_date,purchase_sum,purchase_count,current_balance_avg_sum,current_balance_sum,current_debit_turn_sum,current_credit_turn_sum,card_type
0,fe60b594364f9f636266ed1ef4f89c32,Ж,1985,2020-01-29,R,Гусь-Хрустальный,0,Договор на текущий счет для дебетовой карты,a83cbc33f164deae41b3339141923cc7,Visa Platinum Rewards,2019,2021,16600,71,39700,25700,220600,201000,dc
1,3012cabca5885ed53d348d6e57dab5de,М,1951,2009-09-24,R,Ишимбай,0,Договор на текущий счет для дебетовой карты,8dae17a830bb05d151034df618efbcad,VISA Classic,2019,-1,0,0,1900,1000,6200,3000,dc
2,d871ef96820b6c7a1ada8e01a772724e,Ж,1982,2006-12-25,R,Юрга,0,Договор на текущий счет для дебетовой карты,429ca8c43cdc5f3d8c9efc9069ee3fa6,NaN,-1,-1,0,0,0,0,0,0,dc
3,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,Томск,0,Договор на текущий счет для дебетовой карты,e7f4adb9187b867ebea15503298437a3,Visa Rewards,2021,-1,24300,118,0,0,35400,35400,cc
4,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,Томск,0,Договор на текущий счет для дебетовой карты,e7d13882154e965dca7070eb8d626f77,Eurocard/MasterCard World,2018,2022,24300,118,0,0,35400,35400,cc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371578,d69d3201104ab393c0638839a7284ad7,М,1953,2018-08-08,R,Пятигорск,200000,Кредитная карта,a78c73e84e893179de17071583cf5084,NaN,-1,-1,0,0,0,300,9900,10100,dc
371579,a936fb30e2268d2874cdcaa221032915,М,1997,2022-05-12,R,Кемерово,15000,Кредитная карта,e3304eaf55891a175b6abf8030b99da1,NaN,-1,-1,15000,33,0,0,15000,15000,dc
371580,a9cf0bb4f06fa321704ced777e993b33,М,1983,2021-10-15,R,Санкт-Петербург,15000,Кредитная карта,c53331e855fdda10b01fa1b11d96292c,NaN,-1,-1,600,5,0,0,1100,1100,dc
371581,f69eb17242ca85eb21349dc08220afb8,Ж,1986,2022-02-12,R,Уфа,15000,Кредитная карта,fe20a230ac51078059b03220558ed853,NaN,-1,-1,0,0,0,0,1100,1100,dc
371582,93237191eddf8dec77cc947c3c086358,Ж,1959,2012-07-19,R,Москва,30000,Кредитная карта,db7d3058f19b8bab645cf33efd86330d,NaN,-1,-1,9900,19,0,0,29900,29900,dc

In [59]:
data = data.drop_duplicates() # Избавление от дубликатов записей

In [60]:
a = data['card_id'].value_counts()
a

899e767a957c195ed319a58238474242    39
bb609973024e83acdc33b86518958f8b    25
8a259e220b3e37c8eaffc29527d5ade6    25
a1eaf5482998db17b0643c785282f24c    24
f22ad7a6a51f9f35ab56f0baafc64580    24
                                    ..
bcfd99a051ed8d72c4259be0b9df9b0c     1
ae777bff43479b2a7dcc511046e77b8d     1
be76733d780bf1a87603fc28cb5bbe7d     1
5b35221a74880f4ed56dc6c95a6c1d50     1
db7d3058f19b8bab645cf33efd86330d     1
Name: card_id, Length: 22583, dtype: int64

In [61]:
data.shape

(240397, 19)

Поиск актуальных записей

In [62]:
listUniqueCardID = data.card_id.unique()
len(listUniqueCardID)

22583

In [63]:
import threading
import sys

In [64]:
def getlistEqualPartsOfNumberParts(intNub, intParts):
  d, r = divmod(intNub, intParts)
  return [d + (1 if i < r else 0) for i in range(intParts)]

In [65]:
gl_ActualUserData = pd.DataFrame()

In [130]:
def th_get_ActualUserData(gl_DataFrame, listUniqueCardID, intIndex):
    local_UsersData = pd.DataFrame()
    for i in range(len(listUniqueCardID)):
        strPDCall = f"card_id == '{listUniqueCardID[i]}'" # Запрос

        #f_Data = data.query(strPDCall)
        #print( listUniqueCardID[i] , '-', f_Data.shape)

        local_Data = data.query(strPDCall).drop_duplicates()
        #print( listUniqueCardID[i] , '---', local_Data.shape,'\n')

        if (local_Data.shape[0] != 1):
              
            maxDebet =  local_Data['current_debit_turn_sum'].max()
            maxCredet = local_Data['current_credit_turn_sum'].max()
            
            thisDB = local_Data.query(f"current_debit_turn_sum == {maxDebet} & current_credit_turn_sum == {maxCredet}")
            
        else:
            thisDB = local_Data
        
        #print(i, "-", thisDB.shape, "-", listUniqueCardID[i],'\n')

        local_UsersData = pd.concat([local_UsersData, thisDB]) 
           
        #print(local_UsersData.shape)

    local_UsersData.to_csv(f'New_CSV_{intIndex}.csv')

    gl_DataFrame = pd.concat([gl_DataFrame, local_UsersData]) 
    #print(gl_DataFrame.shape)
    #gl_DataFrame = pd.concat([ActualUserData, gl_DataFrame])
    print(f'Thread {intIndex} is done !')
    sys.exit

In [ ]:
listParts = getlistEqualPartsOfNumberParts(len(listUniqueCardID),int(len(listUniqueCardID)/500))
listThreads = []
intCount = 0

for i in range(len(listParts)):

    if listParts[i] == 0 :
        break
    print(f'Thread {i} from {intCount} to {intCount+listParts[i]} is start - {listParts[i]}')
    listThreads.append( threading.Thread( name=f'Thread_{i}', target=th_get_ActualUserData, args=(gl_ActualUserData, listUniqueCardID[ intCount: intCount+listParts[i] ],i , ) ))
    intCount += listParts[i]+1
    listThreads[i].start()

In [94]:
#gl_ActualUserData

In [131]:
#listThreads = []
#listThreads.append( threading.Thread( target=th_get_ActualUserData, args=(gl_ActualUserData, listUniqueCardID[ 0: 500],1 , ) ))
#listThreads[0].start()

a83cbc33f164deae41b3339141923cc7 --- (10, 19)

0 - (1, 19) - a83cbc33f164deae41b3339141923cc7

(1, 19)
8dae17a830bb05d151034df618efbcad --- (24, 19)

1 - (1, 19) - 8dae17a830bb05d151034df618efbcad

(2, 19)
429ca8c43cdc5f3d8c9efc9069ee3fa6 --- (1, 19)

2 - (1, 19) - 429ca8c43cdc5f3d8c9efc9069ee3fa6

(3, 19)
e7f4adb9187b867ebea15503298437a3 --- (22, 19)

3 - (1, 19) - e7f4adb9187b867ebea15503298437a3

(4, 19)
(4, 19)
Thread 1 is done !

In [96]:
#ActualUserData = pd.DataFrame()

0 - (1, 19) - a83cbc33f164deae41b3339141923cc7
1 - (1, 19) - 8dae17a830bb05d151034df618efbcad

In [97]:
#for i in range(len(listUniqueCardID)):
#    strPDCall = f"card_id == '{listUniqueCardID[i]}'"
#    maxDebet = data.query(strPDCall)['current_debit_turn_sum'].max()
#    maxCredet = data.query(strPDCall)['current_credit_turn_sum'].max()
#    #print(strPDCall)
#    thisDB = data.query(f"current_debit_turn_sum == {maxDebet} & current_credit_turn_sum == {maxCredet}")
#    ActualUserData = pd.concat([ActualUserData, thisDB])
#    print(i)

2 - (20191, 19) - 429ca8c43cdc5f3d8c9efc9069ee3fa6
3 - (14, 19) - e7f4adb9187b867ebea15503298437a3

Thread 3 is done !

Мужчины / Женщины