In [49]:
import pandas as pd

In [50]:
data = pd.read_csv('Raw_data.csv')

In [51]:
data

,client_id,gender,birth_date,create_date,nonresident_flag,businessman_flag,city,term,contract_sum,product_category_name,...,card_type_name,start_date,fact_close_date,purchase_sum,purchase_count,current_balance_avg_sum,current_balance_sum,current_debit_turn_sum,current_credit_turn_sum,card_type
0,fe60b594364f9f636266ed1ef4f89c32,Ж,1985,2020-01-29,R,0,Гусь-Хрустальный,NaN,0.0,Договор на текущий счет для дебетовой карты,...,Visa Platinum Rewards,2019.0,2021.0,16600.0,71,39700.0,25700.0,220600.0,201000.0,dc
1,3012cabca5885ed53d348d6e57dab5de,М,1951,2009-09-24,R,0,Ишимбай,NaN,0.0,Договор на текущий счет для дебетовой карты,...,VISA Classic,2019.0,NaN,0.0,0,1900.0,1000.0,6200.0,3000.0,dc
2,d871ef96820b6c7a1ada8e01a772724e,Ж,1982,2006-12-25,R,0,Юрга,NaN,0.0,Договор на текущий счет для дебетовой карты,...,NaN,NaN,NaN,0.0,0,0.0,0.0,0.0,0.0,dc
3,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,0,Томск,NaN,0.0,Договор на текущий счет для дебетовой карты,...,Visa Rewards,2021.0,NaN,24300.0,118,0.0,0.0,35400.0,35400.0,cc
4,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,0,Томск,NaN,0.0,Договор на текущий счет для дебетовой карты,...,Eurocard/MasterCard World,2018.0,2022.0,24300.0,118,0.0,0.0,35400.0,35400.0,cc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371578,d69d3201104ab393c0638839a7284ad7,М,1953,2018-08-08,R,0,Пятигорск,NaN,200000.0,Кредитная карта,...,NaN,NaN,NaN,0.0,0,0.0,300.0,9900.0,10100.0,dc
371579,a936fb30e2268d2874cdcaa221032915,М,1997,2022-05-12,R,0,Кемерово,NaN,15000.0,Кредитная карта,...,NaN,NaN,NaN,15000.0,33,0.0,0.0,15000.0,15000.0,dc
371580,a9cf0bb4f06fa321704ced777e993b33,М,1983,2021-10-15,R,0,Санкт-Петербург,NaN,15000.0,Кредитная карта,...,NaN,NaN,NaN,600.0,5,0.0,0.0,1100.0,1100.0,dc
371581,f69eb17242ca85eb21349dc08220afb8,Ж,1986,2022-02-12,R,0,Уфа,NaN,15000.0,Кредитная карта,...,NaN,NaN,NaN,0.0,0,0.0,0.0,1100.0,1100.0,dc
371582,93237191eddf8dec77cc947c3c086358,Ж,1959,2012-07-19,R,0,Москва,NaN,30000.0,Кредитная карта,...,NaN,NaN,NaN,9900.0,19,0.0,0.0,29900.0,29900.0,dc

In [52]:
data.shape

(371583, 21)

Подготовка базы данных

In [53]:
data = data.drop(['term','businessman_flag'], axis=1)

In [54]:
data = data.fillna({'start_date': -1, 'fact_close_date': -1})

In [55]:
data = data.astype({'start_date': int, 'fact_close_date': int , 'purchase_sum':int ,'purchase_sum':int ,'contract_sum':int , 'current_balance_avg_sum':int , 'current_balance_sum':int, 'current_debit_turn_sum':int, 'current_credit_turn_sum':int})

In [56]:
data.shape

(371583, 19)

In [183]:
a = data['card_id'].value_counts()
a

899e767a957c195ed319a58238474242    39
bb609973024e83acdc33b86518958f8b    25
8a259e220b3e37c8eaffc29527d5ade6    25
a1eaf5482998db17b0643c785282f24c    24
f22ad7a6a51f9f35ab56f0baafc64580    24
                                    ..
bcfd99a051ed8d72c4259be0b9df9b0c     1
ae777bff43479b2a7dcc511046e77b8d     1
be76733d780bf1a87603fc28cb5bbe7d     1
5b35221a74880f4ed56dc6c95a6c1d50     1
db7d3058f19b8bab645cf33efd86330d     1
Name: card_id, Length: 22583, dtype: int64

In [58]:
data

,client_id,gender,birth_date,create_date,nonresident_flag,city,contract_sum,product_category_name,card_id,card_type_name,start_date,fact_close_date,purchase_sum,purchase_count,current_balance_avg_sum,current_balance_sum,current_debit_turn_sum,current_credit_turn_sum,card_type
0,fe60b594364f9f636266ed1ef4f89c32,Ж,1985,2020-01-29,R,Гусь-Хрустальный,0,Договор на текущий счет для дебетовой карты,a83cbc33f164deae41b3339141923cc7,Visa Platinum Rewards,2019,2021,16600,71,39700,25700,220600,201000,dc
1,3012cabca5885ed53d348d6e57dab5de,М,1951,2009-09-24,R,Ишимбай,0,Договор на текущий счет для дебетовой карты,8dae17a830bb05d151034df618efbcad,VISA Classic,2019,-1,0,0,1900,1000,6200,3000,dc
2,d871ef96820b6c7a1ada8e01a772724e,Ж,1982,2006-12-25,R,Юрга,0,Договор на текущий счет для дебетовой карты,429ca8c43cdc5f3d8c9efc9069ee3fa6,NaN,-1,-1,0,0,0,0,0,0,dc
3,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,Томск,0,Договор на текущий счет для дебетовой карты,e7f4adb9187b867ebea15503298437a3,Visa Rewards,2021,-1,24300,118,0,0,35400,35400,cc
4,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,Томск,0,Договор на текущий счет для дебетовой карты,e7d13882154e965dca7070eb8d626f77,Eurocard/MasterCard World,2018,2022,24300,118,0,0,35400,35400,cc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371578,d69d3201104ab393c0638839a7284ad7,М,1953,2018-08-08,R,Пятигорск,200000,Кредитная карта,a78c73e84e893179de17071583cf5084,NaN,-1,-1,0,0,0,300,9900,10100,dc
371579,a936fb30e2268d2874cdcaa221032915,М,1997,2022-05-12,R,Кемерово,15000,Кредитная карта,e3304eaf55891a175b6abf8030b99da1,NaN,-1,-1,15000,33,0,0,15000,15000,dc
371580,a9cf0bb4f06fa321704ced777e993b33,М,1983,2021-10-15,R,Санкт-Петербург,15000,Кредитная карта,c53331e855fdda10b01fa1b11d96292c,NaN,-1,-1,600,5,0,0,1100,1100,dc
371581,f69eb17242ca85eb21349dc08220afb8,Ж,1986,2022-02-12,R,Уфа,15000,Кредитная карта,fe20a230ac51078059b03220558ed853,NaN,-1,-1,0,0,0,0,1100,1100,dc
371582,93237191eddf8dec77cc947c3c086358,Ж,1959,2012-07-19,R,Москва,30000,Кредитная карта,db7d3058f19b8bab645cf33efd86330d,NaN,-1,-1,9900,19,0,0,29900,29900,dc

In [59]:
data = data.drop_duplicates() # Избавление от дубликатов записей

In [184]:
a = data['card_id'].value_counts()
a

899e767a957c195ed319a58238474242    39
bb609973024e83acdc33b86518958f8b    25
8a259e220b3e37c8eaffc29527d5ade6    25
a1eaf5482998db17b0643c785282f24c    24
f22ad7a6a51f9f35ab56f0baafc64580    24
                                    ..
bcfd99a051ed8d72c4259be0b9df9b0c     1
ae777bff43479b2a7dcc511046e77b8d     1
be76733d780bf1a87603fc28cb5bbe7d     1
5b35221a74880f4ed56dc6c95a6c1d50     1
db7d3058f19b8bab645cf33efd86330d     1
Name: card_id, Length: 22583, dtype: int64

In [61]:
data.shape

(240397, 19)

Поиск актуальных записей

In [62]:
listUniqueCardID = data.card_id.unique()
len(listUniqueCardID)

22583

In [63]:
import threading
import sys

In [64]:
def getlistEqualPartsOfNumberParts(intNub, intParts):
  d, r = divmod(intNub, intParts)
  return [d + (1 if i < r else 0) for i in range(intParts)]

In [136]:
def th_get_ActualUserData(gl_DataFrame, listUniqueCardID, intIndex):
    local_UsersData = pd.DataFrame()
    for i in range(len(listUniqueCardID)):
        if float(i%100) == 0:
            print(i)
            
        strPDCall = f"card_id == '{listUniqueCardID[i]}'" # Запрос

        #f_Data = data.query(strPDCall)
        #print( listUniqueCardID[i] , '-', f_Data.shape)

        local_Data = data.query(strPDCall).drop_duplicates()
        #print( listUniqueCardID[i] , '---', local_Data.shape,'\n')

        if (local_Data.shape[0] != 1):
              
            maxDebet =  local_Data['current_debit_turn_sum'].max()
            maxCredet = local_Data['current_credit_turn_sum'].max()
            
            thisDB = local_Data.query(f"current_debit_turn_sum == {maxDebet} & current_credit_turn_sum == {maxCredet}")
            
        else:
            thisDB = local_Data
        
        #print(i, "-", thisDB.shape, "-", listUniqueCardID[i],'\n')

        local_UsersData = pd.concat([local_UsersData, thisDB]) 
           
        #print(local_UsersData.shape)

    local_UsersData.to_csv(f'New_CSV_{intIndex}.csv')

    gl_DataFrame = pd.concat([gl_DataFrame, local_UsersData]) 
    print(gl_DataFrame.shape)

    print(f'Thread {intIndex} is done !')
    sys.exit

In [ ]:
listParts = getlistEqualPartsOfNumberParts(len(listUniqueCardID),int(len(listUniqueCardID)/500))
listThreads = []
intCount = 0

for i in range(len(listParts)):

    if listParts[i] == 0 :
        break
    print(f'Thread {i} from {intCount} to {intCount+listParts[i]} is start - {listParts[i]}')
    listThreads.append( threading.Thread( name=f'Thread_{i}', target=th_get_ActualUserData, args=(gl_ActualUserData, listUniqueCardID[ intCount: intCount+listParts[i] ],i , ) ))
    intCount += listParts[i]+1
    listThreads[i].start()

In [171]:
gl_ActualUserData = pd.DataFrame()

for i in range(len(listParts)):
    gl_ActualUserData = pd.concat([gl_ActualUserData, pd.read_csv(f'Source_f_2/New_CSV_{i}.csv').drop_duplicates()]) 
gl_ActualUserData.shape

(16313, 20)

In [172]:
count = 0
for i in range(len(listParts)):
    count += pd.read_csv(f'Source_f_2/New_CSV_{i}.csv').shape[0]
count

16313

In [175]:
gl_ActualUserData

,Unnamed: 0,client_id,gender,birth_date,create_date,nonresident_flag,city,contract_sum,product_category_name,card_id,card_type_name,start_date,fact_close_date,purchase_sum,purchase_count,current_balance_avg_sum,current_balance_sum,current_debit_turn_sum,current_credit_turn_sum,card_type
0,0,fe60b594364f9f636266ed1ef4f89c32,Ж,1985,2020-01-29,R,Гусь-Хрустальный,0,Договор на текущий счет для дебетовой карты,a83cbc33f164deae41b3339141923cc7,Visa Platinum Rewards,2019,2021,16600,71,39700,25700,220600,201000,dc
1,237315,3012cabca5885ed53d348d6e57dab5de,М,1951,2009-09-24,R,Ишимбай,0,Договор на текущий счет для дебетовой карты,8dae17a830bb05d151034df618efbcad,VISA Classic,2019,-1,4900,2,38000,26800,56300,31300,dc
2,2,d871ef96820b6c7a1ada8e01a772724e,Ж,1982,2006-12-25,R,Юрга,0,Договор на текущий счет для дебетовой карты,429ca8c43cdc5f3d8c9efc9069ee3fa6,NaN,-1,-1,0,0,0,0,0,0,dc
3,131863,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,Томск,0,Договор на текущий счет для дебетовой карты,e7f4adb9187b867ebea15503298437a3,Visa Rewards,2021,-1,47800,12,0,0,51500,51500,cc
4,131864,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,Томск,0,Договор на текущий счет для дебетовой карты,e7d13882154e965dca7070eb8d626f77,Eurocard/MasterCard World,2018,2022,47800,12,0,0,51500,51500,cc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,371570,9acb18399b830419bac9653b52754646,М,1986,2015-05-20,R,Уфа,0,Договор на текущий счет для дебетовой карты,d090cb20c22e2643ec366daf8d26d646,NaN,-1,-1,0,0,0,0,0,0,dc
326,371577,8b3206ca8d77aa2446824971f47c531b,Ж,1996,2022-04-28,R,Казань,30000,Кредитная карта,5a0041efbd5832765caf8b9f861bffa3,NaN,-1,-1,22700,7,0,0,22700,22700,dc
327,371578,d69d3201104ab393c0638839a7284ad7,М,1953,2018-08-08,R,Пятигорск,200000,Кредитная карта,a78c73e84e893179de17071583cf5084,NaN,-1,-1,0,0,0,300,9900,10100,dc
328,371579,a936fb30e2268d2874cdcaa221032915,М,1997,2022-05-12,R,Кемерово,15000,Кредитная карта,e3304eaf55891a175b6abf8030b99da1,NaN,-1,-1,15000,33,0,0,15000,15000,dc
329,371582,93237191eddf8dec77cc947c3c086358,Ж,1959,2012-07-19,R,Москва,30000,Кредитная карта,db7d3058f19b8bab645cf33efd86330d,NaN,-1,-1,9900,19,0,0,29900,29900,dc

In [176]:
gl_ActualUserData.drop(['Unnamed: 0'], axis=1)

,client_id,gender,birth_date,create_date,nonresident_flag,city,contract_sum,product_category_name,card_id,card_type_name,start_date,fact_close_date,purchase_sum,purchase_count,current_balance_avg_sum,current_balance_sum,current_debit_turn_sum,current_credit_turn_sum,card_type
0,fe60b594364f9f636266ed1ef4f89c32,Ж,1985,2020-01-29,R,Гусь-Хрустальный,0,Договор на текущий счет для дебетовой карты,a83cbc33f164deae41b3339141923cc7,Visa Platinum Rewards,2019,2021,16600,71,39700,25700,220600,201000,dc
1,3012cabca5885ed53d348d6e57dab5de,М,1951,2009-09-24,R,Ишимбай,0,Договор на текущий счет для дебетовой карты,8dae17a830bb05d151034df618efbcad,VISA Classic,2019,-1,4900,2,38000,26800,56300,31300,dc
2,d871ef96820b6c7a1ada8e01a772724e,Ж,1982,2006-12-25,R,Юрга,0,Договор на текущий счет для дебетовой карты,429ca8c43cdc5f3d8c9efc9069ee3fa6,NaN,-1,-1,0,0,0,0,0,0,dc
3,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,Томск,0,Договор на текущий счет для дебетовой карты,e7f4adb9187b867ebea15503298437a3,Visa Rewards,2021,-1,47800,12,0,0,51500,51500,cc
4,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,Томск,0,Договор на текущий счет для дебетовой карты,e7d13882154e965dca7070eb8d626f77,Eurocard/MasterCard World,2018,2022,47800,12,0,0,51500,51500,cc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,9acb18399b830419bac9653b52754646,М,1986,2015-05-20,R,Уфа,0,Договор на текущий счет для дебетовой карты,d090cb20c22e2643ec366daf8d26d646,NaN,-1,-1,0,0,0,0,0,0,dc
326,8b3206ca8d77aa2446824971f47c531b,Ж,1996,2022-04-28,R,Казань,30000,Кредитная карта,5a0041efbd5832765caf8b9f861bffa3,NaN,-1,-1,22700,7,0,0,22700,22700,dc
327,d69d3201104ab393c0638839a7284ad7,М,1953,2018-08-08,R,Пятигорск,200000,Кредитная карта,a78c73e84e893179de17071583cf5084,NaN,-1,-1,0,0,0,300,9900,10100,dc
328,a936fb30e2268d2874cdcaa221032915,М,1997,2022-05-12,R,Кемерово,15000,Кредитная карта,e3304eaf55891a175b6abf8030b99da1,NaN,-1,-1,15000,33,0,0,15000,15000,dc
329,93237191eddf8dec77cc947c3c086358,Ж,1959,2012-07-19,R,Москва,30000,Кредитная карта,db7d3058f19b8bab645cf33efd86330d,NaN,-1,-1,9900,19,0,0,29900,29900,dc

In [ ]:
#listThreads = []
#listThreads.append( threading.Thread( target=th_get_ActualUserData, args=(gl_ActualUserData, listUniqueCardID[ 0: 500],1 , ) ))
#listThreads[0].start()

In [177]:
gl_ActualUserData.to_csv('RTG_CSV.csv')

Мужчины / Женщины

In [301]:
ManToWoman = gl_ActualUserData.drop_duplicates(subset=['client_id'])
ManToWoman = ManToWoman['gender'].value_counts()

In [302]:
ManToWoman = ManToWoman.to_frame()
ManToWoman = ManToWoman.rename(columns = {0:'gender', 1:'count'})
ManToWoman

   gender
Ж    6340
М    5716

In [294]:
ManToWoman.to_json('ManToWoman.json')

Количество приобретённых карт за год

In [277]:
import datetime

now = datetime.datetime.now()

In [278]:
cardTypeDF = gl_ActualUserData.query(f"start_date >= {now.year}-1")
cardTypeDF

,Unnamed: 0,client_id,gender,birth_date,create_date,nonresident_flag,city,contract_sum,product_category_name,card_id,card_type_name,start_date,fact_close_date,purchase_sum,purchase_count,current_balance_avg_sum,current_balance_sum,current_debit_turn_sum,current_credit_turn_sum,card_type
3,131863,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,Томск,0,Договор на текущий счет для дебетовой карты,e7f4adb9187b867ebea15503298437a3,Visa Rewards,2021,-1,47800,12,0,0,51500,51500,cc
7,211127,069a78f2b5f78554eaa5dbb61d84fc24,Ж,1960,2018-08-17,R,Нижний Новгород,0,Договор на текущий счет для дебетовой карты,179c20dc702f8b3553b10e1b083cc8b9,VISA Classic Light,2021,-1,100,2,2700,4100,11100,10100,dc
10,29471,f15f2554a0ce062adfb77b89583f312f,М,1989,2010-12-16,R,Туапсе,0,Договор на текущий счет для дебетовой карты,bae6632af4c6d36013a6a6a594a261d6,Eurocard/MasterCard Mass,2021,-1,9100,23,32700,50200,110400,151900,dc
17,235936,c0558c09e6d8967a4f7da4e631af0931,Ж,1992,2018-02-09,R,Уфа,0,Договор на текущий счет для дебетовой карты,29aef8d895f0ba76f3493b58996acd89,МИР Debit,2021,-1,1100,1,400,0,2900,2900,dc
24,209966,b6bdc6ad9870be654af83757cc1e1823,Ж,1993,2011-09-13,R,Уфа,0,Договор на текущий счет для дебетовой карты,36d2401aee9a26300691fefba9b31ff7,"Дебет карта ПС МИР ""Бюджетная""",2021,-1,0,0,2600,40000,66600,106600,dc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,371362,6c3347ad0cc240e20366a1a0b09bca0a,М,1970,2020-06-11,R,Уфа,0,Договор на текущий счет для дебетовой карты,dccd72269a1b128a42c18e61f9f70cf6,МИР СКБ ЗП,2022,-1,0,0,6800,15600,0,15600,dc
318,371357,984e5ad59b98958dde5b395011852abc,Ж,1996,2022-02-16,R,Уфа,0,Договор на текущий счет для дебетовой карты,615d994b55876b010020388483901006,MasterCard Electronic,2022,-1,3600,17,400,0,11900,11500,dc
321,371431,bc661fc9c5da2c9aa896e45ea668ba06,М,1973,2013-04-17,R,Смоленск,0,Договор на текущий счет для дебетовой карты,53aa0c8480996c8773abff9bc263c903,"Дебет карта ПС МИР ""Бюджетная""",2022,-1,2100,7,600,400,2100,2000,dc
323,371486,66a3d5e9a035415aaa39298bf5f13a03,М,1989,2018-12-12,R,Москва,0,Договор на текущий счет для дебетовой карты,d26bfffaeeaad088cdcd7d5d6135a4e3,MIR Privilege Plus,2022,-1,0,0,6500,100000,0,100000,dc
324,371569,a5aa5918ab2d581c3584e712ecf503f4,М,1997,2018-06-14,R,Москва,0,Договор на текущий счет для дебетовой карты,9688af6309629f15b8f9890e9a6b5416,MIR Privilege Plus,2022,-1,0,0,0,0,0,0,dc

In [279]:
cardTypeDF.isnull().sum()

Unnamed: 0                  0
client_id                   0
gender                      0
birth_date                  0
create_date                 0
nonresident_flag            0
city                       56
contract_sum                0
product_category_name       0
card_id                     0
card_type_name              0
start_date                  0
fact_close_date             0
purchase_sum                0
purchase_count              0
current_balance_avg_sum     0
current_balance_sum         0
current_debit_turn_sum      0
current_credit_turn_sum     0
card_type                   0
dtype: int64

In [280]:
listCardType = cardTypeDF['card_type_name'].unique()
listCardType

array(['Visa Rewards', 'VISA Classic Light', 'Eurocard/MasterCard Mass',
       'МИР Debit', 'Дебет карта ПС МИР "Бюджетная"', 'VISA Classic',
       'МИР СКБ', 'Eurocard/MasterCard Platinum', 'МИР СКБ ЗП',
       'Eurocard/MasterCard World', 'Eurocard/MasterCard Gold',
       'VISA Gold', 'Priority Pass', 'MasterCard World Elite',
       'MasterCard Electronic', 'Visa Platinum Rewards', 'VISA Infinite',
       'MasterCard Black Edition', 'VISA Platinum', 'МИР Копилка',
       'Eurocard/MasterCard Virt', 'Visa Signature', 'MIR Supreme',
       'MIR Privilege Plus'], dtype=object)

In [281]:
cardTypeDF = cardTypeDF['card_type_name'].value_counts()
cardTypeDF

Visa Platinum Rewards             1247
Visa Rewards                      1062
Дебет карта ПС МИР "Бюджетная"     611
МИР Debit                          520
VISA Classic                       355
VISA Gold                          246
Eurocard/MasterCard Mass           211
VISA Classic Light                 174
МИР СКБ                            164
Eurocard/MasterCard World          157
MasterCard Electronic              136
МИР СКБ ЗП                         131
Eurocard/MasterCard Platinum       118
Priority Pass                       72
MasterCard World Elite              58
Eurocard/MasterCard Gold            54
VISA Infinite                       40
MIR Supreme                         32
Visa Signature                      25
MIR Privilege Plus                  20
VISA Platinum                       13
MasterCard Black Edition            10
Eurocard/MasterCard Virt             4
МИР Копилка                          1
Name: card_type_name, dtype: int64

In [282]:
sum = cardTypeDF.values.sum()
sum

5461

In [283]:
listCreditSys = ['Visa','MIR','МИР','MasterCard','Maestro']
listCreditSysCount = [0]*len(listCreditSys)
print(listCreditSysCount)

[0, 0, 0, 0, 0]

In [284]:
print('Visa' in "Visa Signature")
print('MIR' in "Visa Signature")
print('Visa'.capitalize() in "Visa Signature")

True
False
True

In [285]:
for i in range(len(cardTypeDF.index)):
    for j in range(len(listCreditSys)):
        if (listCreditSys[j] in cardTypeDF.index[i]) or (listCreditSys[j] in cardTypeDF.index[i].capitalize()):
            listCreditSysCount[j] += cardTypeDF.values[i]
print(listCreditSys)
print(listCreditSysCount)

['Visa', 'MIR', 'МИР', 'MasterCard', 'Maestro']
[3162, 52, 1427, 748, 0]

In [290]:
list_tuples  = list(zip(listCreditSys, listCreditSysCount))
NewBankCard = pd.DataFrame(list_tuples, columns=['listCreditSys', 'listCreditSysCount']) 
NewBankCard.to_json('NewBankCard.json')

Кол-во действующих банковских карт

In [289]:
ValueCardData = gl_ActualUserData.query(f"start_date != -1 & fact_close_date == -1")
ValueCardData

,Unnamed: 0,client_id,gender,birth_date,create_date,nonresident_flag,city,contract_sum,product_category_name,card_id,card_type_name,start_date,fact_close_date,purchase_sum,purchase_count,current_balance_avg_sum,current_balance_sum,current_debit_turn_sum,current_credit_turn_sum,card_type
1,237315,3012cabca5885ed53d348d6e57dab5de,М,1951,2009-09-24,R,Ишимбай,0,Договор на текущий счет для дебетовой карты,8dae17a830bb05d151034df618efbcad,VISA Classic,2019,-1,4900,2,38000,26800,56300,31300,dc
3,131863,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,Томск,0,Договор на текущий счет для дебетовой карты,e7f4adb9187b867ebea15503298437a3,Visa Rewards,2021,-1,47800,12,0,0,51500,51500,cc
5,5,c79f7d18334216f7bd6c40a05e4a0335,Ж,1980,2015-06-19,R,Октябрьский,0,Договор на текущий счет для дебетовой карты,e3baaf11e34b13c3cbb93fd6e2f6096e,МИР Debit,2019,-1,0,0,12700,1000,15000,7800,dc
7,211127,069a78f2b5f78554eaa5dbb61d84fc24,Ж,1960,2018-08-17,R,Нижний Новгород,0,Договор на текущий счет для дебетовой карты,179c20dc702f8b3553b10e1b083cc8b9,VISA Classic Light,2021,-1,100,2,2700,4100,11100,10100,dc
9,29470,f15f2554a0ce062adfb77b89583f312f,М,1989,2010-12-16,R,Туапсе,0,Договор на текущий счет для дебетовой карты,ca3b0bab14de9b04132ecb84c2b01f6c,Eurocard/MasterCard Mass,2019,-1,9100,23,32700,50200,110400,151900,dc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,371362,6c3347ad0cc240e20366a1a0b09bca0a,М,1970,2020-06-11,R,Уфа,0,Договор на текущий счет для дебетовой карты,dccd72269a1b128a42c18e61f9f70cf6,МИР СКБ ЗП,2022,-1,0,0,6800,15600,0,15600,dc
318,371357,984e5ad59b98958dde5b395011852abc,Ж,1996,2022-02-16,R,Уфа,0,Договор на текущий счет для дебетовой карты,615d994b55876b010020388483901006,MasterCard Electronic,2022,-1,3600,17,400,0,11900,11500,dc
321,371431,bc661fc9c5da2c9aa896e45ea668ba06,М,1973,2013-04-17,R,Смоленск,0,Договор на текущий счет для дебетовой карты,53aa0c8480996c8773abff9bc263c903,"Дебет карта ПС МИР ""Бюджетная""",2022,-1,2100,7,600,400,2100,2000,dc
323,371486,66a3d5e9a035415aaa39298bf5f13a03,М,1989,2018-12-12,R,Москва,0,Договор на текущий счет для дебетовой карты,d26bfffaeeaad088cdcd7d5d6135a4e3,MIR Privilege Plus,2022,-1,0,0,6500,100000,0,100000,dc
324,371569,a5aa5918ab2d581c3584e712ecf503f4,М,1997,2018-06-14,R,Москва,0,Договор на текущий счет для дебетовой карты,9688af6309629f15b8f9890e9a6b5416,MIR Privilege Plus,2022,-1,0,0,0,0,0,0,dc

In [306]:
ValueCardData = ValueCardData.groupby('client_id').agg({'card_type_name':'sum', })
ValueCardData

                                                  card_type_name
client_id
00021cd7b00abc41b066921e5b24e599                    Visa Rewards
0005900275b1c05a92710268a0bfdcdd           MasterCard Electronic
0020438a8e6c83a5dd7a5a8afdf6188b                       МИР Debit
003a838018aa1387ad5103bbcdc2d5e3                       МИР Debit
003aba44c70fa03a377f2bec3b871080           Visa Platinum Rewards
...                                                          ...
ffc3ade73ab43964e1418362f8a2576d    Eurocard/MasterCard Platinum
ffca75257b4148e064882ec897536e0d                    VISA Classic
ffd07e6797a5d1801cde105327329c46  Дебет карта ПС МИР "Бюджетная"
ffd64561f67b6d21d85480e59d3563a7           MasterCard Electronic
fffa15d3b8556f7bebc83f80181a6ffe           Visa Platinum Rewards

[6993 rows x 1 columns]